# Generated by Django 5.0.3 on 2024-10-21 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'staff',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=15)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_address', models.TextField()),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('items_ordered', models.JSONField()),
                ('order_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_mode', models.CharField(max_length=50)),
                ('delivery_method', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('staff_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant_admin_dashboard.staff')),
            ],
            options={
                'db_table': 'order_info',
            },
        ),
    ]
