# Generated by Django 5.0.3 on 2024-10-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_admin_dashboard', '0004_alter_order_staff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='staff_id',
            field=models.CharField(max_length=15),
        ),
    ]
