# Generated by Django 5.0.3 on 2024-11-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_admin_dashboard', '0007_registereduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('admin', 'Admin'), ('staff', 'Staff')], default='staff', max_length=10),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='role_id',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
