# Generated by Django 5.0.3 on 2024-11-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_admin_dashboard', '0008_registereduser_role_registereduser_role_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registereduser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff')], default='staff', max_length=10),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='role_id',
            field=models.IntegerField(default='0', max_length=50),
        ),
    ]
